- moz_do/views.py
> Add CORS header to responses

- static/do.js
- static/results.html
Can only do limited tests locally due to CORS...
> Use all new API

- scanner/src/tasks.py
And add tag to docker image ref
> scanner: pass DB_URL through

- moz_do/models.py
- moz_do/views.py
This add dependencies to the 'package' API endpoint (at the moment, it's recursive - but that can and probably will change) (issue #16)
It also adds a new 'parents' endpoint - same usage as the 'package with version' endpoint (issue #15)
> add parents and dependencies

- util/import.py
- util/test_data.json
From an environment with the moz_do package, run import.py
> util for test data

- moz_do/models.py
For some reason using 2 underscore in a name fails - no idea why :/
> Add fields to the reports table

- README.md
- depobs/Dockerfile
- depobs/website/scans.py
- depobs/website/views.py
- depobs/worker/celeryconfig.py
- depobs/worker/tasks.py
- docker-compose.yml
fixes #22 
Changes:
* Add a /scan endpoint
* add `CELERY_` prefix to `BROKER_URL` for worker; add it to api
> Fix 22 run scans from api

- depobs/Dockerfile
- depobs/database_requirements.txt
- depobs/website_requirements.txt
Changes:
* de-dup requirements files since pip complains when requirements files include duplicate requirements
* add database_requirements.txt to API pip install
> de-dup db requirements

- depobs/Dockerfile
- depobs/website/__init__.py
- depobs/website/do.py
- depobs/website/views.py
- docker-compose.yml
refactoring around flask conventions:
* use `FLASK_ENV` instead of `DEBUG`
* use default flask static file handler
* rename moz_do flask app instance to app
> flask config

- README.md
- docker-compose.yml
- util/call_task_with_result.sh
> Add oneoff worker runner

- depobs/Dockerfile.worker
> worker: install web requirements in image

- util/call_task_with_result.sh
Tests the scorer task (breaks readme directions).
> test score_package task

- depobs/website/models.py
- depobs/worker/tasks.py
> 20200313 graph build

- depobs/Dockerfile
> more dockerflow reqs

- depobs/website/static/do.js
- depobs/website/static/results.html
> Handle error responses

- depobs/database/schema.py
- depobs/website/models.py
- depobs/website/views.py
- depobs/worker/celeryconfig.py
- depobs/worker/tasks.py
- docker-compose.yml
> Fix 84 scan missing packages

- depobs/website/scans.py
- depobs/website/views.py
- depobs/worker/tasks.py
> Fix 79 build reports and score after scan

- depobs/database/schema.py
- depobs/website/models.py
- depobs/website/views.py
> Fix 97 return task id and status

- depobs/website/static/do.js
- depobs/website/static/index.html
Colour Vulnerabilities banner according to max vulns.
'This package' and 'Dependencies' -> bold.
Right align scoring numbers.
> Vulnerability UI tweaks

- depobs/requirements.txt
- depobs/website/scans.py
- depobs/website/views.py
- depobs/worker/tasks.py
> Fix 83 check package exists before scan

- depobs/website/models.py
- depobs/website/views.py
Part of #107 
Example json response:
```
{
"package": "minimist", 
"version": "0.0.10", 
"vulnerabilities": [
{
"severity": "low", 
"title": "Prototype Pollution", 
"url": "https://npmjs.com/advisories/1179"
}
]
}
```
@g-k first endpoint I've done so please check I've not done anything stupid ;)
I can implement the UI changes if/when this is merged.
> Add vulnerabilities endpoint

- depobs/database/mixins.py
fix error trying to serialize task_status from task_id=None
> db: handle missing task id

- depobs/Dockerfile
- depobs/requirements.txt
- depobs/website/models.py
- depobs/website/views.py
Add graphviz graphs for debugging
> debug graphs

- depobs/website/models.py
- depobs/website/views.py
> Dont start a new scan if theres an existing one

- depobs/Dockerfile
- depobs/requirements.txt
- depobs/website/models.py
- depobs/worker/tasks.py
- tests/test_outer_in_iter.py
- util/run_tests.sh
fixes #130 
Requires additional QA and unit testing to verify correct counts and scores.
> Fix 130 score all deps

- README.md
> readme: add links to scoring docs

- depobs/website/static/do.js
- depobs/worker/tasks.py
> papercut fixes

- depobs/website/views.py
> small code fixes

- depobs/website/static/do.js
> Add NPM link

- depobs/website/static/do.js
> Trim npmsio_score to 2 decimal places

- depobs/website/__init__.py
- depobs/website/do.py
- depobs/website/scans.py
- depobs/website/views.py
refactor to use flask blueprints and instantiate the app in `do.py:main` for #75
> blueprints

- .gitignore
- depobs/website/do.py
- docker-compose.yml
> add create_app factory fn

- .circleci/config.yml
print a diff to see changes before failing with check
refs: #166
> ci: output diff before check

- .circleci/config.yml
- pyproject.toml
- setup.cfg
- util/format_diff.sh
- util/run_tests.sh
- util/run_tests_with_coverage.sh
Changes:
* addresses most of (except being able to apply the patches generated in the container): https://github.com/mozilla-services/dependency-observatory/issues/169
* add a unit-test CCI job that runs unit tests with coverage
> check more in ci

- depobs/requirements.txt
- depobs/website/config.py
- depobs/website/do.py
- depobs/website/views.py
This is probably not very idiomatic as I'm finding my way around flask, but it works, meaning:
* heartbeat, lbheartbeat and version endpoints are handled by the dockerflow package
* all requests are logged in mozlog format (and we can add fields later on)
> Dockerflowed

- .circleci/config.yml
- tests/website/test_dockerflow.py
- util/run_tests_with_coverage.sh
fixes: #177 and failing unit tests
> util: exit with test error code in CI

- depobs/website/models.py
> web: convert package_dependencies to declarative defn

- depobs/website/do.py
I had planned several hours to work through this patch. It took 5 minutes...
> dockerflow: add db to heartbeat

- depobs/scanner/__init__.py
- depobs/scanner/docker/containers.py
- depobs/scanner/docker/log_reader.py
- depobs/scanner/models/language.py
- depobs/scanner/pipelines/postprocess.py
- depobs/scanner/pipelines/run_repo_tasks.py
- depobs/website/config.py
- depobs/website/models.py
- depobs/worker/tasks.py
- setup.cfg
refs: #162 part 2
fixes: #129 with installing from tarball urls as @psiinon suggested
> Fix 162 combine with scanner part 2

- .circleci/config.yml
- depobs/scanner/clients/cratesio.py
- depobs/scanner/rx_util.py
- setup.cfg
Add limited type checking for a few scanner folders.
> type check

- depobs/.dockerignore
- depobs/Dockerfile
- docker-compose.yml
serve it from `/app/depobs/version.json` on the container
> fix version.json

- depobs/requirements.txt
- depobs/scanner/pytest.ini
- depobs/website/config.py
- depobs/worker/tasks.py
> Fix 162 combine with scanner part 6

- depobs/website/static/do.js
- depobs/website/static/index.html
Rather than asking the user to come back.
Doesnt display any progress, but thats for later :)
Fixes #126
> Poll for response

- depobs/website/static/do.js
- depobs/website/static/index.html
> Display vulnerabilities

- depobs/scanner/clients/cratesio.py
- depobs/scanner/clients/npm_registry.py
- depobs/scanner/clients/npmsio.py
- depobs/scanner/docker/containers.py
- depobs/scanner/docker/images.py
- depobs/scanner/docker/log_reader.py
- depobs/scanner/graph_util.py
- depobs/scanner/models/nodejs.py
- depobs/scanner/models/rust.py
- depobs/scanner/pipelines/crate_graph.py
- depobs/scanner/pipelines/dep_graph.py
- depobs/scanner/pipelines/fetch_package_data.py
- depobs/scanner/pipelines/find_dep_files.py
- depobs/scanner/pipelines/find_git_refs.py
- depobs/scanner/pipelines/github_metadata.py
- depobs/scanner/pipelines/postprocess.py
- depobs/scanner/pipelines/run_repo_tasks.py
- depobs/scanner/pipelines/rust_changelog.py
- depobs/scanner/pipelines/save_to_db.py
- depobs/scanner/rx_util.py
> scanner: get logger with __name__

- depobs/website/models.py
- setup.cfg
> web: add type hints to models.py

- depobs/website/static/do.js
> Link to the NPMS IO Score

- depobs/website/static/do.js
- depobs/website/static/index.html
> Show error messages

- depobs/worker/scoring.py
switched the iterator for #141 before scoring could accommodate it
> worker: revert scoring change

- depobs/worker/scoring.py
- tests/worker/test_scoring.py
> test score package and children

- depobs/scanner/pipelines/save_to_db.py
> scanner: fix import errors in save_to_db pipeline

- README.md
- depobs/database/models.py
- depobs/website/config.py
- depobs/website/views.py
- depobs/worker/scoring.py
- depobs/worker/tasks.py
- docker-compose.yml
- tests/worker/test_scoring.py
We use the npms.io scores to score dependent packages.
> Fetch missing npmsio scores

- depobs/database/models.py
- depobs/scanner/graph_traversal.py
- depobs/scanner/graph_util.py
- depobs/worker/scoring.py
- depobs/worker/tasks.py
- tests/scanner/unit/test_graph_traversal.py
- tests/worker/test_scoring.py
> Fix 141 score cycles

- depobs/website/views.py
Functional Tests:
for a known package name already in the db:
> web: hit the npm reg to fetch new versions of known package names

- depobs/website/config.py
- depobs/website/do.py
- depobs/website/score_details/blueprint.py
- depobs/website/views.py
Adds an app called `score_details` and redirects the old `/graphs/` endpoint to it.
> Add score details

- depobs/website/score_details/blueprint.py
> more score details

- depobs/website/config.py
> web: fix config keyerror image -> images

- depobs/database/models.py
Not using it anywhere yet, thats for the next PRs :)
Part of #282
> Added score_view

- .circleci/config.yml
- README.md
- setup.cfg
- tests/docker/test_docker_log_reader.py
- tests/fixtures/__heartbeat__200.json
- tests/fixtures/__version__keys.json
- tests/scanner/unit/test_github_models.py
- tests/scanner/unit/test_graph_traversal.py
- tests/scanner/unit/test_nodejs_models.py
- tests/scanner/unit/test_quiz_util.py
- tests/util/test_serialize_util.py
- tests/website/test_dockerflow.py
- tests/worker/test_scoring.py
- tests/worker/test_validators.py
- util/e2e_test.sh
- util/run_tests.sh
- util/run_tests_with_coverage.sh
Changes:
* normalize docker container names
* fix test-images config
* fix util test scripts to not rely on compose and mounts
* add a simple e2e script to test the API (fixes: #75 , refs: #239)
> CI: check basic scan

- tests/website/test_dockerflow.py
fix typo in dockerflow heartbeat url and unmark it as a unit test since it hits the DB
> web: fix heartbeat dockerflow test

- depobs/website/score_details/blueprint.py
- depobs/worker/scoring.py
- depobs/worker/tasks.py
- tests/worker/test_scoring.py
Adds dot graphs with labelled data for individual score components e.g.
* http://localhost:8000/score_details/score_component_graph/1/npmsio_score
* http://localhost:8000/score_details/score_component_graph/1/directVulnsHigh_score
* http://localhost:8000/score_details/score_component_graph/1/authors
* http://localhost:8000/score_details/score_component_graph/1/contributors
* http://localhost:8000/score_details/score_component_graph/1/npmsio_score
* http://localhost:8000/score_details/score_component_graph/1/immediate_deps
* http://localhost:8000/score_details/score_component_graph/1/all_deps
> score details graph

- util/find_package_json_files.sh
- util/run_cwd_in_image.sh
> repo scan utils

- .circleci/config.yml
- depobs/database/models.py
- depobs/website/views.py
- tests/conftest.py
- tests/website/test_api.py
- util/e2e_test.sh
Changes:
* Add more API tests (refs: #60 #76) 
* Fix NameError for a registered package name w/o a version param
* default to loading npm reg entry shasum and tarball columns
> Add api test

- depobs/worker/tasks.py
> worker: log less job info

- depobs/clients/aiohttp_client_config.py
- depobs/clients/github.py
- depobs/clients/npm_registry.py
- depobs/clients/npmsio.py
- depobs/website/config.py
Adds a configurable `base_url` to http clients (except crates.io) for #286
> 286 configure client base urls

- Dockerfile
- depobs/clients/npmsio.py
- depobs/website/static/do.js
- depobs/website/static/index.html
- depobs/website/views.py
adds warning to fixes #260 
finishes the last part of #282
> 260 flag old npmsio scores

- depobs/worker/tasks.py
> worker: scan tarball without url

- depobs/website/static/do.js
- depobs/website/static/index.html
> web: mv inline toggle parents handler to do.js

- depobs/database/models.py
- kubernetes/README.md
- util/build_and_redeploy_image.sh
> Fix 207 add score histogram to stats

- depobs/worker/validators.py
- tests/worker/test_validators.py
> worker: improve package name and version error messages

- .circleci/config.yml
- .gitignore
- Dockerfile
- depobs/website/do.py
- tests/website/test_dockerflow.py
- util/build_and_redeploy_image.sh
> move version.json to container /app/ dir

- bin/docker-entrypoint.sh
> bin: disable uwsgi multithreading

- bin/docker-entrypoint.sh
- docker-compose.yml
- kubernetes/deployment.yaml
Changes
* Adds PROCS and THREADS env vars for the non-dev web server
* changes FLASK_APP env var to match uwsgi param
> env var updates

- Dockerfile
- bin/docker-entrypoint.sh
> uwsgi fixes

- bin/docker-entrypoint.sh
for when the env vars aren't set
> bin: set default PROCS and THREADS

- uwsgi.ini
> uwsgi: disable logs

- depobs/website/config.py
- depobs/website/views.py
- depobs/worker/k8s.py
- depobs/worker/tasks.py
- kubernetes/deployment.yaml
> fix 368 multiple k8s contexts 

- depobs/website/config.py
- depobs/worker/k8s.py
- depobs/worker/tasks.py
fixes: #370 
functional tested by setting TTL to 0 and making sure the job was deleted
> Fix 370 set job ttl

- depobs/website/static/do.js
- depobs/website/templates/search_index.html
fixes: #360 
Adds links to make a new GH issue
functional tested by passing invalid package and job names
> Fix 360 err with request

- tests/worker/test_serializers.py
refs: PR #411
Forgot to commit it with the original PR.
> worker: add test for deserializing npm registry entries

- README.md
- depobs/database/models.py
- depobs/website/config.py
- depobs/website/schemas.py
- depobs/website/static/do.js
- depobs/website/views.py
- depobs/worker/k8s.py
- tests/website/test_api.py
refs: #404 
Initial web UI, api, and config changes for #404
> pubsub api

- README.md
- depobs/database/models.py
- depobs/website/templates/package_changelog.html
- depobs/website/templates/package_report.html
- depobs/website/templates/scan_job_logs.html
- depobs/website/templates/search_index.html
- depobs/website/views.py
- depobs/worker/tasks.py
Changes:
* fixes for scanning all versions of an npm package
* add package changelog page
> Add package changelog

- depobs/worker/gcp.py
skip creating subscription there too
> worker: fix 403s from receive_pubsub_messages

- depobs/worker/tasks.py
Changes:
* reduce worker log volume
* log the copied config and not the general config for scan tarball tasks
> fewer worker logs

- bin/docker-entrypoint.sh
> set gcloud container/use_application_default_credentials true

- depobs/worker/k8s.py
fix issue with the listed context not being found
> worker: use kubernetes load_kube_config

- .circleci/config.yml
- util/build_scan_images.sh
They slow down CI significantly.
> Disable unused scan images

- depobs/website/templates/package_changelog.html
- depobs/website/templates/package_report.html
> web: open npm package links in new tab

- depobs/database/models.py
- depobs/website/static/graph.js
- depobs/website/templates/statistics.html
- depobs/website/views.py
- migrations/versions/63f04096672e_add_old_scoring_view.py
Added a drop down menu to the statistics page which allows you to change which scoring algorithm the graphs display data for.
> Added score view for old scoring algorithm

- depobs/worker/k8s.py
I think this is how its done...
> Add security context for jobs

- README.md
- kubernetes/README.md
- kubernetes/deployment.yaml
- util/run_tests.sh
- util/run_tests_with_coverage.sh
fixes #397 (except db migrations)
> Fix 397 k8s dev volumes

- depobs/worker/serializers.py
- tests/worker/test_serializers.py
> worker: fix deserializing empty CWE ids

- depobs/website/static/scan_job_logs_page.js
- depobs/website/templates/scan_job_logs.html
- docker-compose.yml
> web: refresh without meta el

- depobs/database/models.py
- depobs/website/templates/base.html
- depobs/website/templates/dependencies_table.html
- depobs/website/templates/recent_package_reports.html
- depobs/website/views.py
> add /recent_package_reports

- depobs/database/models.py
- depobs/website/templates/package_changelog.html
- depobs/website/views.py
- depobs/worker/tasks.py
> Fix 429 diff links

- .circleci/config.yml
- README.md
> Fix 179 track test coverage

- depobs/database/enums.py
- depobs/requirements.txt
- depobs/website/auth.py
- depobs/website/config.py
- depobs/website/views.py
- kubernetes/deployment.yaml
- migrations/versions/9a41ac493101_add_canceled_status_to_scan_status_enum.py
- tests/conftest.py
- tests/website/test_api.py
fixes: #77 #456 (cancels queued scans but not scan k8s jobs)
> Fix 77 scan basic auth

- Makefile
- kubernetes/README.md
> 551 add falco for localdev

- depobs/website/views.py
refs: https://github.com/mozilla-services/python-dockerflow/blob/master/docs/changelog.rst#2020100-2020-10-05
> web: use dockerflow g.request_id
