mozilla-services/dependency-observatory

moz_do/views.py
Allows /static/ to map to the contents of the static directory in the root of the project.
=> add temporary support for static files

depobs/Dockerfile
for consistency with the worker image and new language features.
=> docker: switch web image to 3.8-buster

depobs/website/static/do.js, depobs/website/views.py
refs: #66
Also:
* limit them to GET only
* combine `show_package_by_name` and `show_package_by_name_and_version`
* switch `/package` to `/packages` for plurality consistency with `/parents`
=> web: change API to use query params for package name and version

depobs/worker/tasks.py
refs: #100
Should make debugging and celery cancellation via timeouts easier.
functional test:
=> worker: convert build_report_tree `.delay` calls to immediate calls

depobs/website/models.py, depobs/worker/tasks.py
refs: #100
changes:
* track visited deps in build report tree hopefully fixing issue 100
* logging tweaks
* model fetching error handling for missing dep versions and subjects
functional test:
=> scoring debugging

depobs/website/models.py, depobs/worker/tasks.py
fixes: #100
Changes:
* only score the subgraph from the latest link in which the package is a parent (we might find the dependency in multiple graphs but only care the the score for the most recent one) 
* fetch all links for a graph once instead of querying along the way (perf-wise assuming relatively few links in a graph and that the dependency uses most of them)
=> Fix 100 score latest graph

depobs/website/models.py, depobs/worker/tasks.py
refs #100 (last fix was incomplete / wrong)
changes:
* keep a set of scored pkg name, version tuples instead of visited package tuples
* return scored package reports for those packages from `get_ordered_package_deps_and_reports` renamed from `get_ordered_package_deps` and `score_package_and_children`
=> track scored deps since they get re-added for scoring

depobs/website/models.py, depobs/website/views.py, depobs/worker/tasks.py
This added an 'status' field to the report table.
This allows us to expose the fact we've had an error to the UI, although
its not a very nice error atm :)
To test:
http://localhost:8000/?manager=npm&package=async&version=3.2.0
Initially this will show the 'come back later' message.
But after the job fails it will show the 'unexpected error' message.
=> Expose the fact we've had an error

depobs/worker/tasks.py
The direct_dep_reports param is mandatory, and it looks like specifying an empty list as a default is not recommended.
=> Fix call to score_package

depobs/website/config.py
`./depobs/scanner/clients/npm_registry.py` uses `npm_auth_token`
=> web: rename npm_pat to npm_auth_token to fix using the wrong name

depobs/Dockerfile, depobs/requirements.txt
Changes:
* remove unused OS packages for docker CLI
* remove some -scanner dev requirements
This should speed up the build-images CI job.
edit: looks like it doesn't hurt
The last master build took ~3m https://circleci.com/workflow-run/b541cbea-7e57-4aba-afb0-f084aead0d86 and this one took 2m6s https://app.circleci.com/pipelines/github/mozilla-services/dependency-observatory/414/workflows/5a10131b-2442-45b9-865c-6115803c1aa3
=> prune deps

depobs/requirements.txt, depobs/scanner/graph_traversal.py, depobs/website/config.py, depobs/worker/scoring.py, depobs/worker/tasks.py, setup.cfg, tests/scanner/unit/test_graph_traversal.py, tests/worker/test_outer_in_iter.py, tests/worker/test_scoring.py, util/run_tests_with_coverage.sh
Changes for #141:
* move scoring to `worker.scoring`
* move DAG iter alg to `scanner.graph_traversal` and add a graph iter alg
* add `pytest-mock` to requirements
* add unit tests for `score_package`
* remove some unused / unreachable code from `score_package`
* fix util run pkg with coverage showing old reports
=> Test scoring

README.md, depobs/website/config.py, depobs/website/scans.py, depobs/website/static/do.js, depobs/website/views.py, depobs/worker/tasks.py
fixes: #234 removes the npms.io check and updates the UI to show the description field for 404 errors 
Functional Tests:
=> Fix 234 improve package not found errors

depobs/database/models.py, depobs/website/scans.py, depobs/worker/scoring.py, depobs/worker/tasks.py, tests/worker/test_scoring.py
Changes:
* remove the `POST /score` endpoint
* fetch and count direct vulns using `database.models.Advisory` aggregated in `collections.Counter`s
=> refactor scoring

.circleci/config.yml, README.md
Adds a CI job to use for:
* E2E tests #75 
* db-backed API tests #76 
* running a monitor or basic load test #239
Moves the coverage test results to `unit-test-htmlcov` and `test-image-htmlcov` so they don't stomp on each other. TODO: combine coverage output or run unit tests in test-images.
=> ci: add db backed tests against built images

docker-compose.yml
As per https://stackoverflow.com/questions/53170709/docker-compose-could-not-open-directory-permisson-denied
Worth double checking this doesnt break for anyone else before merging.
=> Tweak build to work with SE Linux

depobs/scanner/clients/aiohttp_client_config.py, depobs/scanner/clients/cratesio.py, depobs/scanner/clients/npm_registry.py, depobs/scanner/clients/npmsio.py, depobs/scanner/docker/containers.py, depobs/scanner/graph_util.py, depobs/scanner/pipelines/run_repo_tasks.py, depobs/website/config.py, depobs/website/views.py, depobs/worker/tasks.py, setup.cfg
Changes:
* replaces some argparse namespaces with configs for #162
* enable type checking `worker.tasks`
* pluralize run repo tasks config var names for lists
* delete a bunch of run repo tasks code
=> Fix 162 argparse namespaces

depobs/database/models.py
This defines the score code letter in a view as well so that it can be changed on the fly.
Also tweaked the score_view so that it is easier to use in practice (included the id and scoring_date)
=> Add score_code_view

depobs/website/views.py, tests/website/test_api.py
Pretend the worker is an upstream service returning 500 was confusing to debug.
=> web: return 502 for errorred scans

depobs/database/models.py
Don't try to use `PackageReport`'s dependencies<->parents relationship on `PackageScorePackage`
=> db: fix sqla loading errors fetching report parents

Dockerfile
gcloud is needed to auth the client with the jobs kubernetes cluster
=> Install gcloud sdk in container image

kubernetes/README.md, kubernetes/deployment.yaml
Instructions to create secret without committing to repo, then updates to api workload to use the service account key.
=> Allow local development to access gcp pubsub

depobs/clients/aiohttp_client.py
CI was failing with despite the check on `if config.get("additional_headers", None):`
changing the following line to:
```python
additional_headers: Dict[str, str] = config["additional_headers"]
```
also failed.
I believe this is related to typeddict newness, but a quick search didn't reveal an upstream issue in mypy.
```console
depobs/clients/aiohttp_client.py: note: In function "aiohttp_session":
depobs/clients/aiohttp_client.py:57:23: error: Item "None" of
"Optional[Dict[str, str]]" has no attribute "__iter__" (not iterable) 
[union-attr]
for header in additional_headers:
^
depobs/clients/aiohttp_client.py:58:31: error: Value of type
"Optional[Dict[str, str]]" is not indexable  [index]
headers[header] = additional_headers[header]
^
Found 2 errors in 1 file (checked 35 source files) …
```
=> fix type-check CI failure clients additional_headers

scan_envs/Dockerfile, scan_envs/docker-entrypoint.sh, util/build_scan_images.sh
refs: #404 
Changes:
* add curl and gcloud to scan images
* install cargo audit in rust scan image
* add `util/build_scan_images.sh` to build scan images without `docker-compose` to use with the minikube docker
* have gcloud cache config at `CLOUDSDK_CONFIG` in a temp dir 
* tee output to a temp file and publish it to pubsub as one message (up to 10MB, but haven't run into that limit yet)
* add env vars:
* `CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE` to configure gcloud for use outside GCP
* `GCP_PROJECT_ID` to set the default gcloud project
* `GCP_PUBSUB_TOPIC` where to publish messages
* `JOB_NAME` the k8s job name for joining with the initial scan request
=> scan env updates

Makefile, bin/docker-entrypoint.sh, kubernetes/README.md, kubernetes/deployment.yaml, util/build_and_redeploy_image.sh, util/build_image.sh, util/recreate_cluster.sh, util/redeploy_image.sh
refs: #404 
Changes:
* Add makefile and refactor util scripts
* change main image worker command to call run (not implemented)
* in k8s:
* drop pod logs perms for `job-admin` svc account
* drop job-runner for api deployment
* add worker deployment with secret mount and env vars for pubsub (`JOB_STATUS_PUBSUB_TOPIC` and `JOB_STATUS_PUBSUB_SUBSCRIPTION`) and GCP config (`GCP_PROJECT_ID` and `GOOGLE_APPLICATION_CREDENTIALS`)
* remove env vars `DEFAULT_JOB_SERVICE_ACCOUNT_NAME`, `UNTRUSTED_JOB_NAMESPACE`, `UNTRUSTED_JOB_SERVICE_ACCOUNT_NAME`, and `GOOGLE_APPLICATION_CREDENTIALS` w/ secret mount from api deployment
=> add worker process config

depobs/website/templates/scan_job_logs.html
Change:
* Add a newline to the template so scan logs don't all render to one very wide line
=> web: show one json result per line one scan job logs page

depobs/worker/tasks.py, depobs/worker/validators.py, tests/worker/test_validators.py
fixes: #450 and changes npm package version regex to match leading `v` without an `=`
=> Fix 450 skip npm prerelease versions

depobs/worker/tasks.py
fixes #499 again (this part https://github.com/mozilla-services/dependency-observatory/issues/499#issuecomment-680933732)
=> worker: don't fail scan for missing npm reg or npms.io score

Dockerfile, bin/docker-entrypoint.sh, bin/e2e_test.sh
fixes: #239 (except for the load testing part)
functional test from within the image:
```console
$ make api-shell
app@api-7ddc676ccf-mqhj5:/app$ ./bin/e2e_test.sh
testing http://localhost:8000/__heartbeat__
/__heartbeat__ response matched fixture ./tests/fixtures/__heartbeat__200.json
testing http://localhost:8000/__lbheartbeat__
/__lbheartbeat__ matched fixture ./tests/fixtures/__lbheartbeat__200.json
testing http://localhost:8000/__version__
/__version__ keys matched fixture ./tests/fixtures/__version__keys.json
started scan with id 3
sleeping for one second between progress checks
scan_status: queued
scan_status: queued
scan_status: queued
scan_status: queued
scan_status: started
...
scan_status: started
scan_status: succeeded
scan succeeded. Report response:
<!DOCTYPE HTML PUBLIC …
```
=> add e2e-test $api_url [fixture_directory] to docker entrypoint

depobs/worker/k8s.py
manually clean up or use a job TTL
cc @erkolson we don't have TTL right now, so we'll have to clean up old jobs, but I think it'll help with debugging.
=> worker: don't delete jobs

web-uwsgi.ini, worker-uwsgi.ini
fail for unknown options and use one interpreter instead of hosting
multiple services
=> enable strict mode and single-interpreter in uwsgi configs
